version: "3"

services:
  moody-broker:
    image: eclipse-mosquitto
    networks:
      - mqtt
    ports:
      - 1883:1883
    command:
      ["mosquitto", "-v"]

  moody-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - postgres
    ports: 
      - 5432:5432
    volumes:
      - ./postgres/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./postgres/data:/var/lib/postgresql/data

  moody-mongo:
    image: mongo
    networks:
      - mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db

  moody-api-gw:
    image: nginx:latest
    volumes:
      - ./api_gateway/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-back
      - nginx-front
    ports:
      - 8080:80
    depends_on:
      - moody-neural
      - moody-dataset
      - moody-service

  moody-neural:
    build: ./neural
    networks:
      - nginx-back
      - mongo
    depends_on:
      - moody-mongo

  moody-dataset:
    build: ./dataset
    networks:
      - nginx-back
      - mongo
    depends_on:
      - moody-mongo

  moody-service:
    build: ./service
    networks:
      - nginx-back
      - postgres
    depends_on:
      - moody-postgres

  moody-situation:
    build: ./situation
    networks:
      - nginx-back
      - postgres
    depends_on:
      - moody-postgres

  moody-gateway:
    build: ./gateway
    volumes: 
      - ./gateway/conf.json:/conf.json
    networks:
      - mqtt
      - nginx-front
    ports:
      - 7000:80
    depends_on:
      - moody-broker
      - moody-api-gw

  moody-adminpanel:
    build: ./admin_panel
    networks:
      - nginx-front
    ports:
      - 3000:80
    depends_on:
      - moody-gateway


networks:
  mqtt:
  nginx-front:
  nginx-back:
  postgres:
  mongo: