version: "3"

services:
  moody-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - postgres
    volumes:
      - ./postgres/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./postgres/data:/var/lib/postgresql/data

  moody-mongo:
    image: mongo
    restart: always
    networks:
      - mongo
    volumes:
      - ./mongo/data:/data/db

  moody-api-gw:
    image: nginx:latest
    restart: always
    volumes:
      - ./api_gateway/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-back
    ports:
      - 8080:80
    depends_on:
      - moody-neural
      - moody-dataset
      - moody-service

  moody-neural:
    image: ./neural
    restart: always
    networks:
      - nginx-back
      - mongo
    depends_on:
      - moody-mongo

  moody-dataset:
    image: ./dataset
    restart: always
    networks:
      - nginx-back
      - mongo
    depends_on:
      - moody-mongo

  moody-service:
    image: ./service
    restart: always
    networks:
      - nginx-back
      - postgres
    depends_on:
      - moody-postgres

  moody-situation:
    image: ./situation
    restart: always
    networks:
      - nginx-back
      - postgres
    depends_on:
      - moody-postgres

networks:
  nginx-back:
  postgres:
  mongo: