version: "3"

services:
  moody-broker:
    image: eclipse-mosquitto
    volumes:

    networks:
      - mqtt
    ports:
      - 1883:1883
    command:
      ["mosquitto", "-v"]

  moody-gateway:
    image: abathargh/moody-go-gateway:latest
    volumes:
      - ./gateway/data:/data
    networks:
      - mqtt
      - gw-front
    ports:
      - 7000:7000
    depends_on:
      - moody-broker

  moody-adminpanel:
    image: abathargh/moody-go-adminpanel:latest
    networks:
      - gw-front
    ports:
      - 3000:3000
    depends_on:
      - moody-gateway

networks:
  mqtt:
  gw-front: