version: "3"

services:
  moody-activity:
    build: abathargh/moody-go-activity
    restart: always
    networks:
      - nginx-back
      - postgres
    depends_on:
      - moody-activity-db

  moody-activity-db:
    build: abathargh/moody-go-activity_pg
    restart: always
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - activity-pg:/var/lib/postgresql/data

  moody-dataset:
    build: abathargh/moody-dataset
    restart: always
    networks:
      - nginx-back
      - mongo
    depends_on:
      - moody-dataset-db

  moody-dataset-db:
    image: mongo
    restart: always
    networks:
      - mongo
    ports:
      - 27017:27017
    volumes:
      - dataset-mongo:/data/db

  moody-api-gw:
    image: nginx:latest
    restart: always
    volumes:
      - ./api_gateway/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-front
      - nginx-back
    ports:
      - 8080:80
    depends_on:
      - moody-activity
      - moody-dataset

volumes:
  activity-pg:
    external: false
  dataset-mongo:
    external: false

networks:
  mqtt:
  nginx-front:
  nginx-back:
  postgres:
  mongo: