FROM arm32v7/golang:1.14-alpine AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOARCH=arm \
    GOARM=7 \
    GOOS=linux

WORKDIR /app
COPY . .

RUN go mod download
RUN go build -o moody-gateway .

FROM scratch

COPY --from=builder /app/moody-gateway /app/moody-gateway
COPY conf.json .

EXPOSE 80
ENTRYPOINT ["/app/moody-gateway"]